name: Update index of thumbnails

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: "45 2 * * *"

permissions:
  contents: write

concurrency:
  group: Generate index
  cancel-in-progress: true

jobs:
  apps:
    name: "Generate index"
    runs-on: windows-latest #ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install lftp

      - run: |
          #choco install lftp
          lftp -c du -a http://thumbnailpacks.libretro.com/ > manifest.tsv
          
      - shell: node {0}
        run: |
          const fs = require('fs');
          const manifest = fs.readFileSync('./manifest.tsv', 'utf-8');
          fs.writeFileSync('./manifest.json', JSON.stringify(manifest.split('\n').map(e => 'http://thumbnailpacks.libretro.com' + e.trimEnd().slice(e.indexOf('\t') + 1)), null, 1));

      - name: Push updated manifest.txt
        shell: pwsh
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config pull.rebase true

          git add manifest.tsv
          git add manifest.json
          git commit -m "Automated manifest update"
          git pull
          git push

          exit 0

      - name: Keepalive Workflow
        if: always()
        uses: gautamkrishnar/keepalive-workflow@v2
